import './globals.css';
import { Inter } from 'next/font/google';

import HeaderNav from '@/components/headerNav';
import ScoreBoard from '@/components/scoreboard/scoreboard';
import ScoreCard from '@/components/scoreboard/scorecard';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <HeaderNav />
        </header>
        <ScoreBoard>
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
          <ScoreCard />
        </ScoreBoard>
        <section className='container mx-auto px-4 mt-5'>{children}</section>
      </body>
    </html>
  );
}
